### ISSUE TITLE
Reloading

### ISSUE THREAD

**Issue by JusticeShultz** [JusticeShultz/ScifiFPSVRGame#3]
User should be able to pull a clip from their left side if they have clips for their gun. User pulls clip and puts it onto a glowing box on the gun, if the user has no ammo clips do not pull a clip, if a user pulls a clip subtract from how many clips are left in the gun. Allow the clips to be droppable and throwable. If the clip enters the glowing zone on the gun it should slide in using a lerp. Old clip should turn into a simple game object with a box collider and rigidbody(Don't worry about despawns for now)

**Comment by alyoshenka** [comment]
Current implementation: user picks up fresh clips from belt on GrabClip, currently bound to left trigger. Clips drop on trigger release, get added back into belt OnTriggerEnter with clip holder, and refill bullet count on collision with gun. This triggers a lerp anim of a clip sliding into the gun.
