### ISSUE TITLE
Height Adjustment

### ISSUE THREAD

**Issue by alyoshenka** [JusticeShultz/ScifiFPSVRGame#9]
At start of game, player should be able to calibrate to their height and have ammo clip location and any other items they are holding set accordingly.

**Comment by alyoshenka** [comment]
This could occur during the initial loading of the game, or could be a setting in he start menu. Ultimately this would also calibrate the floor so the game doesn't start looking as if you are sunk up to your knees

**Comment by JusticeShultz** [comment]
Adding to this task - Some player heights can not currently reach the floor, a universal player height may need to be used to snap in place/offset somehow.

**Comment by JusticeShultz** [comment]
Bumping this issue, some setups make players in the ground and/or short for some reason, height should be locked.
